version: 1
formatters:
  colored:
    "()": "logkiss.ColoredFormatter"
    format: "%(asctime)s %(levelname)s | %(filename)s: %(lineno)d | %(message)s"
    colors:
      levels:
        DEBUG:
          fg: blue
        INFO:
          fg: white
        WARNING:
          fg: black
          bg: yellow
        ERROR:
          fg: black
          bg: red
        CRITICAL:
          fg: black
          bg: bright_red
          style: bold
      elements:
        timestamp:
          fg: white
        filename:
          fg: cyan
        message:
          DEBUG:
            fg: blue
          INFO:
            fg: white
          WARNING:
            fg: black
            bg: yellow
          ERROR:
            fg: black
            bg: red
          CRITICAL:
            fg: black
            bg: bright_red
            style: bold
handlers:
  console:
    class: "logkiss.KissConsoleHandler"
    level: "DEBUG"
    formatter: "colored"
loggers:
  "":
    handlers: ["console"]
    level: "DEBUG"
