site_name: logkiss
site_description: A Simple and Colorful Python Logging Library
site_author: Taka Suzuki
site_url: https://github.com/yourusername/logkiss

repo_name: logkiss
repo_url: https://github.com/yourusername/logkiss
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
  language: en

plugins:
  - search
  - autorefs
  - i18n:
      default_language: en
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: ja
          name: 日本語
          build: true
        - locale: zh
          name: 简体中文
          build: true
      nav_translations:
        ja:
          Home: ホーム
          Installation: インストール
          Usage: 使い方
          API Reference: APIリファレンス
          Core: コア
          Handlers: ハンドラー
          Examples: サンプル
          Contributing: 貢献
        zh:
          Home: 首页
          Installation: 安装
          Usage: 使用方法
          API Reference: API参考
          Core: 核心
          Handlers: 处理器
          Examples: 示例
          Contributing: 贡献
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_category_heading: true
            show_if_no_docstring: false
            heading_level: 2

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API Reference:
    - Core: api/logkiss.md
    - Handlers: api/handlers.md
  - Examples: examples.md
  - Contributing: contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/logkiss
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 日本語
      link: /ja/
      lang: ja
    - name: 简体中文
      link: /zh/
      lang: zh
