formatters:
  hhmmss_fmt:
    fmt: "%(asctime)s %(levelname)s %(message)s"
    datefmt: "%H:%M:%S"
    use_color: true
handlers:
  console:
    class: logging.StreamHandler
    formatter: hhmmss_fmt
    stream: ext://sys.stdout
root:
  level: DEBUG
  handlers: [console]
