version: 1
disable_existing_loggers: false

kiss_config:
  levels:
    debug:
      color: cyan
      style: bold
    info:
      color: green
      style: bold
    warning:
      color: yellow
      style: bold
    error:
      color: white
      background: red
      style: bold
    critical:
      color: white
      background: bright_magenta
      style: 
        - bold
        - blink

  messages:
    debug:
      color: cyan
    info:
      color: green
    warning:
      color: yellow
    error:
      color: red
      style: bold
    critical:
      color: bright_red
      style: bold

  elements:
    timestamp:
      color: blue
      style: dim
    filename:
      color: bright_green
      style: underline
    lineno:
      color: bright_yellow

formatters:
  kiss_default:
    "()": logkiss.ColoredFormatter
    fmt: "%(asctime)s %(levelname)s | %(filename)s:%(lineno)d | %(message)s"
    use_color: true
    
  kiss_detailed:
    "()": logkiss.ColoredFormatter
    fmt: "[%(asctime)s] %(levelname)s [%(filename)s:%(lineno)d] - %(name)s - %(message)s"
    use_color: true

handlers:
  console:
    "()": logkiss.KissConsoleHandler
    level: DEBUG
    formatter: kiss_default
    
  file:
    class: logging.FileHandler
    level: INFO
    formatter: kiss_detailed
    filename: application.log
    mode: a
    
  rotating_file:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: kiss_detailed
    filename: warnings.log
    mode: a
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  app:
    level: DEBUG
    handlers:
      - console
      - file
    propagate: false
    
  app.errors:
    level: ERROR
    handlers:
      - console
      - rotating_file
    propagate: false

root:
  level: INFO
  handlers:
    - console
